{% set version = "1.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tictoc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tictoc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tictoc/tictoc_{{ version }}.tar.gz
  sha256: f05ea4b4142a90b0dc5d10356be3748625ef86bbd0e4399c56455654165ff20c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('tictoc')"           # [not win]
    - "\"%R%\" -e \"library('tictoc')\""  # [win]

about:
  home: http://github.com/collectivemedia/tictoc
  license: Apache-2.0
  summary: This package provides the timing functions 'tic' and 'toc' that can be nested. One can record all timings while a complex script is running, and examine the values later. It is also possible to instrument the timing calls with custom callbacks. In addition, this package provides class 'Stack', implemented as a
    vector, and class 'List', implemented as a list, both of which support operations 'push', 'pop', 'first', 'last' and 'clear'.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - lucapinello
