appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fbkVKCSA2GrLygaj9gVtMJ6n5nIP3+KdHOKFcEmRdXL8OPQicwDuxO/8JjYveWYVuX7wEjO4kkc3sCZ4acZfTMYuZpaaqLobY7w+27fQQVvbLPqYNZ8VCPasp8W8KO/X12XUjljeNy2rwyZMqiMh4evwVD3Zrh19LTNjcMV+b/83Te4Usl3DSpwRGGbfxhqTrgSAtKWL0hjpI6Fdm/CcgPWSizrL7q52PkCpQrjwZxaMQmVq7WpRUlYO0BPspVP/1OyRic/glChOiQoO9KLBQfr9KZtgvc0KyG7y/JUxzjx+HiZGpgz+UfT3T8sT94Bnlv9X7Nh8fmXmD5DM/P6Ccf2p/HgDD/m1nNU7r1+BFplYtMATODN8rDQimmom5a5f3EmN99prf2lXIqZ8ptuhcvQWZkFjKEfIjhrr16BwRbA06zdk8YUFeB6zT+69P1gAdF4lSzOCGWgF6mCmR1TlBmzAdIGSTo26zgsI4BP3EpnkHTc2TKUevpapNS1n2EJNT+WH5lvNawvyxBZcoEHh3ew4JMTxi66/njcSw1fTd7w9v8LnDbMIFrCwYV5dRyAUl9dxJScDtDjprq4H4LBWwwVrzrXm2aos6q8Q8Uf7Oe0HOiGQRMDPlqlrJQOmI2jn0YMTnyWJNsoPwrpyRNxnwI/eowE6mnSxpy6Hm2p3Nhg=}
