travis:
  secure:
    BINSTAR_TOKEN: XeCrp5YqDVkCl3LY5tvF3wkMBQCuk1QpOFfrNKEGVXBGQCF8RfL2qhONJvSdwK+dyZfkYqok8kGP5YxrHl0UGSjd5H6CADi1byEz+loL/scU4u2FWTv8TOPMqJgVuEtxiWsNLjHWTsvDCv2LDmaoWp26Iqs23gYv84ZfzsKbjWfY+9QtZbE2yiO8seVflyIS8Tu1PIUkdpgAMfrPcX/uyRzNpIDCTSgPQLkd7RjPH4Sa8+P4wSKMJ1rhkg4juGHynsTM44VvRnpj4gqgEhC/RTfM+0oOS4Mtd7qqTV7qqfDKIJHsD9si52NQfY8ITZD8ZdUGqyyX8B8w/2kqvlttMWVfbGQuKUquvicVg0+kNGR+BYQFR8CpaAicjexAVFqLNuOqJ9LGaPl3DqmNbEl1KTBDaH/KDKU5TgBgLSWL09pIUQLE6QADieC3bnMvFOLeYFb7H29hNeeXus0D29Xsb6SfzVNs2CUpNsnA5o2mdVf4H+Ke3AZLnazoNeq5T6NfLMHCnByCPsbDtiA339qt2bGulxVvTr0Ekal7iEZiY2/Y8BKcYgvuRwsyJIlLbiqTr4ZVbzFh3FJpuzhfY4Dz7IdcOEIg7l7YCRJksDLslHOU1nf+/Dp3UKae93xKD2b1hcc0NPWOovZwJt/U2KDPcojVNIfvy+7CSq+UdtdALQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
